name: Deploy Backend to EC2 - test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy Backend Code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_NAME }}
        username: ${{ secrets.SSH_USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          scp -r ${{secrets.LOCAL_PATH}} ${{ secrets.SSH_USER_NAME }}@${{ secrets.SSH_HOST }}:/home/${{secrets.SSH_USER_NAME}}/ec2/backend
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER_NAME }}@${{ secrets.SSH_HOST_NAME }} << 'ENDSSH'
            cd /home/${{ secrets.SSH_USER_NAME }}/ec2/backend
            # Run any necessary build or deployment steps here
          ENDSSH

    - name: Run Docker Compose on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_NAME }}
        username: ${{ secrets.SSH_USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER_NAME }}@${{ secrets.SSH_HOST_NAME }} << 'ENDSSH'
            cd /home/${{ secrets.SSH_USER_NAME }}/ec2/backend
            docker-compose -f docker-compose.yml up -d
          ENDSSH
